### ISSUE TITLE
Fix 'Table of Contents' for posts

### ISSUE THREAD

**Issue by rnahumaf** [blankoworld/hugo_theme_adam_eve#10]
It seems that the *table of contents* is broken within new posts. It's only working for the 'about' section.

**Comment by blankoworld** [comment]
Hi @rnahumaf , I will have a look this week-end. Have you check [mainSections option](https://gohugo.io/functions/where/#mainsections) in your config.toml page? Sometimes it have an impact on the result!

**Comment by blankoworld** [comment]
@rnahumaf This problem seems to be the same as https://github.com/Track3/hermit/issues/112 in which they add a specific configuration in `config.toml` file:

```toml
[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1
```
